-- V5__create_member_otp_code.sql
CREATE TABLE MEMBER_OTP_CODE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    CODE_HASH VARCHAR(128) NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    ATTEMPTS INT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IDX_OTP_PHONE_CREATED ON MEMBER_OTP_CODE(PHONE_NUMBER, CREATED_AT);
