-- ============================================================================
-- Initial Schema Creation
-- Version: 1.0
-- Date: 2025-11-28
-- Description: 초기 스키마 생성
-- ============================================================================

-- ============================================================================
-- 1. ADMIN 테이블
-- ============================================================================
CREATE TABLE IF NOT EXISTS ADMIN (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50) NOT NULL DEFAULT 'ADMIN',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ============================================================================
-- 2. PLACE 테이블
-- ============================================================================
CREATE TABLE IF NOT EXISTS PLACE (
    PLACE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    ADDRESS VARCHAR(500) NOT NULL,
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    IMAGE_URL VARCHAR(1000),
    PHONE_NUMBER VARCHAR(20),
    DESCRIPTION VARCHAR(1000),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ============================================================================
-- 3. MEMBER 테이블
-- ============================================================================
CREATE TABLE IF NOT EXISTS MEMBER (
    MEMBER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255),
    PHONE_NUMBER VARCHAR(20),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ============================================================================
-- 4. ROOM 테이블
-- ============================================================================
CREATE TABLE IF NOT EXISTS ROOM (
    ROOM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROOM_NUMBER VARCHAR(50) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    MEMBER_ID BIGINT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_ROOM_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE SET NULL
);

-- ============================================================================
-- 5. TICKET_ISSUANCE 테이블
-- ============================================================================
CREATE TABLE IF NOT EXISTS TICKET_ISSUANCE (
    TICKET_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    ROOM_ID BIGINT NOT NULL,
    ISSUE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_TICKET_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TICKET_ROOM FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID) ON DELETE CASCADE
);

-- ============================================================================
-- 6. SCHEDULE 테이블
-- ============================================================================
CREATE TABLE IF NOT EXISTS SCHEDULE (
    SCHEDULE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL DEFAULT '미지정 일정',
    DESCRIPTION VARCHAR(1000),
    SCHEDULE_DATE DATE NOT NULL,
    START_TIME TIME,
    END_TIME TIME,
    PLACE_ID BIGINT NOT NULL,
    CREATED_BY BIGINT,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_SCHEDULE_PLACE FOREIGN KEY (PLACE_ID) REFERENCES PLACE(PLACE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SCHEDULE_ADMIN FOREIGN KEY (CREATED_BY) REFERENCES ADMIN(ID) ON DELETE SET NULL
);

-- ============================================================================
-- 7. ATTEND 테이블
-- ============================================================================
CREATE TABLE IF NOT EXISTS ATTEND (
    ATTEND_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    SCHEDULE_ID BIGINT NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    ATTENDED_AT TIMESTAMP NULL,
    NOTE VARCHAR(500),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_ATTEND_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ATTEND_SCHEDULE FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE(SCHEDULE_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_ATTEND_STATUS CHECK (STATUS IN ('SCHEDULED', 'PRESENT', 'ABSENT', 'LATE', 'EXCUSED'))
);

-- ============================================================================
-- 8. 인덱스 생성
-- ============================================================================

-- PLACE 인덱스
CREATE INDEX IDX_PLACE_NAME ON PLACE(NAME);

-- MEMBER 인덱스
CREATE INDEX IDX_MEMBER_EMAIL ON MEMBER(EMAIL);
CREATE INDEX IDX_MEMBER_STATUS ON MEMBER(STATUS);

-- SCHEDULE 인덱스
CREATE INDEX IDX_SCHEDULE_DATE ON SCHEDULE(SCHEDULE_DATE);
CREATE INDEX IDX_SCHEDULE_PLACE ON SCHEDULE(PLACE_ID);
CREATE INDEX IDX_SCHEDULE_ACTIVE ON SCHEDULE(IS_ACTIVE);
CREATE INDEX IDX_SCHEDULE_CREATED_BY ON SCHEDULE(CREATED_BY);

-- ATTEND 인덱스
CREATE INDEX IDX_ATTEND_MEMBER ON ATTEND(MEMBER_ID);
CREATE INDEX IDX_ATTEND_SCHEDULE ON ATTEND(SCHEDULE_ID);
CREATE INDEX IDX_ATTEND_STATUS ON ATTEND(STATUS);
CREATE INDEX IDX_ATTEND_MEMBER_SCHEDULE ON ATTEND(MEMBER_ID, SCHEDULE_ID);

-- ROOM 인덱스
CREATE INDEX IDX_ROOM_STATUS ON ROOM(STATUS);
CREATE INDEX IDX_ROOM_MEMBER ON ROOM(MEMBER_ID);

-- TICKET 인덱스
CREATE INDEX IDX_TICKET_MEMBER ON TICKET_ISSUANCE(MEMBER_ID);
CREATE INDEX IDX_TICKET_ROOM ON TICKET_ISSUANCE(ROOM_ID);
CREATE INDEX IDX_TICKET_STATUS ON TICKET_ISSUANCE(STATUS);
