-- V4__create_job_keyword_synonym.sql
CREATE TABLE JOB_KEYWORD_SYNONYM (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PLACE_ID BIGINT NOT NULL,
    KEYWORD VARCHAR(100) NOT NULL,
    CONSTRAINT FK_SYNONYM_PLACE FOREIGN KEY (PLACE_ID) REFERENCES PLACE(PLACE_ID) ON DELETE CASCADE
);
CREATE INDEX IDX_SYNONYM_KEYWORD ON JOB_KEYWORD_SYNONYM(KEYWORD);
CREATE INDEX IDX_SYNONYM_PLACE ON JOB_KEYWORD_SYNONYM(PLACE_ID);
