name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Java version
        run: java -version
      - name: Gradle build
        run: ./gradlew clean build
